<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_This is MyMusicPage</name>
   <tag></tag>
   <elementGuidId>091bdd94-138b-42dd-9f04-fa8493e52c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-white > div.text-white</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0653c1ad-db7c-4a56-9440-288a0ba38160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-white</value>
      <webElementGuid>aafb6052-8e86-4c1a-86a8-6a01a49eca2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is MyMusicPage</value>
      <webElementGuid>54ef747a-ffb4-476b-a09c-15be36f5b8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;mt-[70px]&quot;]/div[@class=&quot;text-white&quot;]/div[@class=&quot;text-white&quot;]</value>
      <webElementGuid>463f49ac-aab7-41d4-9525-87f0abf5507d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div</value>
      <webElementGuid>32e84069-37db-46ed-b2b2-08ae4441c03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nâng cấp tài khoản'])[1]/following::div[3]</value>
      <webElementGuid>8e444c82-e9a0-4f8a-8483-d29732f31501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạo playlist mới'])[1]/following::div[10]</value>
      <webElementGuid>575f0730-0bd4-4169-be34-fdd01eef04c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Song'])[1]/preceding::div[1]</value>
      <webElementGuid>cfd443a8-42ee-4661-a31f-0ec32f4eed97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MV'])[1]/preceding::div[1]</value>
      <webElementGuid>d96b1ffc-06ca-4573-989a-676b4a98c8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>86d01c03-e41a-4007-9dc1-420eff96736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'This is MyMusicPage' or . = 'This is MyMusicPage')]</value>
      <webElementGuid>437b2af5-edde-4e12-96d9-b245cb428497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
